# Generated by Django 2.1.7 on 2019-03-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
    ]
